services:
  - type: web
    name: ai-sdk
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: DEFAULT_MODEL
        value: gpt-4o-mini
      - key: MAX_TOKENS
        value: 2000
      - key: TEMPERATURE
        value: 0.7
      - key: MAX_FILE_SIZE
        value: 10485760
      - key: UPLOAD_DIR
        value: ./uploads 